//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.07 at 02:05:21 PM HST 
//


package org.hackystat.projectbrowser.page.projectportfolio.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Measure" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DefaultValues">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="colorable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="higherBetter" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="defaultLowerThresold" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="defaultHigherThresold" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "measure"
})
@XmlRootElement(name = "Measures")
public class Measures {

    @XmlElement(name = "Measure", required = true)
    protected List<Measures.Measure> measure;

    /**
     * Gets the value of the measure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Measures.Measure }
     * 
     * 
     */
    public List<Measures.Measure> getMeasure() {
        if (measure == null) {
            measure = new ArrayList<Measures.Measure>();
        }
        return this.measure;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DefaultValues">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="colorable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="higherBetter" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="defaultLowerThresold" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="defaultHigherThresold" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "defaultValues"
    })
    public static class Measure {

        @XmlElement(name = "DefaultValues", required = true)
        protected Measures.Measure.DefaultValues defaultValues;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String name;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String alias;

        /**
         * Gets the value of the defaultValues property.
         * 
         * @return
         *     possible object is
         *     {@link Measures.Measure.DefaultValues }
         *     
         */
        public Measures.Measure.DefaultValues getDefaultValues() {
            return defaultValues;
        }

        /**
         * Sets the value of the defaultValues property.
         * 
         * @param value
         *     allowed object is
         *     {@link Measures.Measure.DefaultValues }
         *     
         */
        public void setDefaultValues(Measures.Measure.DefaultValues value) {
            this.defaultValues = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="colorable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="higherBetter" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="defaultLowerThresold" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="defaultHigherThresold" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DefaultValues {

            @XmlAttribute
            protected Boolean colorable;
            @XmlAttribute
            protected Boolean higherBetter;
            @XmlAttribute
            protected Double defaultLowerThresold;
            @XmlAttribute
            protected Double defaultHigherThresold;

            /**
             * Gets the value of the colorable property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isColorable() {
                return colorable;
            }

            /**
             * Sets the value of the colorable property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setColorable(Boolean value) {
                this.colorable = value;
            }

            /**
             * Gets the value of the higherBetter property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isHigherBetter() {
                return higherBetter;
            }

            /**
             * Sets the value of the higherBetter property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setHigherBetter(Boolean value) {
                this.higherBetter = value;
            }

            /**
             * Gets the value of the defaultLowerThresold property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getDefaultLowerThresold() {
                return defaultLowerThresold;
            }

            /**
             * Sets the value of the defaultLowerThresold property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setDefaultLowerThresold(Double value) {
                this.defaultLowerThresold = value;
            }

            /**
             * Gets the value of the defaultHigherThresold property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getDefaultHigherThresold() {
                return defaultHigherThresold;
            }

            /**
             * Sets the value of the defaultHigherThresold property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setDefaultHigherThresold(Double value) {
                this.defaultHigherThresold = value;
            }

        }

    }

}
