//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 11:38:51 AM HST 
//


package org.hackystat.projectbrowser.page.projectportfolio.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hackystat.projectbrowser.page.projectportfolio.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hackystat.projectbrowser.page.projectportfolio.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Measures.Measure.ParticipationParameters }
     * 
     */
    public Measures.Measure.ParticipationParameters createMeasuresMeasureParticipationParameters() {
        return new Measures.Measure.ParticipationParameters();
    }

    /**
     * Create an instance of {@link Measures.Measure.DeviationParameters }
     * 
     */
    public Measures.Measure.DeviationParameters createMeasuresMeasureDeviationParameters() {
        return new Measures.Measure.DeviationParameters();
    }

    /**
     * Create an instance of {@link PortfolioDefinitions }
     * 
     */
    public PortfolioDefinitions createPortfolioDefinitions() {
        return new PortfolioDefinitions();
    }

    /**
     * Create an instance of {@link Measures }
     * 
     */
    public Measures createMeasures() {
        return new Measures();
    }

    /**
     * Create an instance of {@link Measures.Measure }
     * 
     */
    public Measures.Measure createMeasuresMeasure() {
        return new Measures.Measure();
    }

    /**
     * Create an instance of {@link Measures.Measure.StreamTrendParameters }
     * 
     */
    public Measures.Measure.StreamTrendParameters createMeasuresMeasureStreamTrendParameters() {
        return new Measures.Measure.StreamTrendParameters();
    }

}
